"""
Figure: Boundary Suppression as Thermodynamic Friction
======================================================

Three-panel figure:
  (a) Regime net payoff vs. suppression effort (δ_total)
  (b) System dissipation vs. suppression effort
  (c) Cascading friction cost across N suppressed groups

An agent (regime) invests effort in suppressing the boundaries of other
agents (dissidents, minorities, free press). The friction multiplier
Φ > 2 makes suppression system-net-negative, and cascading across
N suppressed groups amplifies the destruction.

Data source: output/data/fig_adversarial_friction.npz
  (generated by scripts/simulations/applied/verify_adversarial_friction.py)

Output: output/figures/fig_adversarial_friction.png

Run:  python scripts/figures/fig_adversarial_friction.py
"""


from __future__ import annotations

import os
import sys

import numpy as np
import matplotlib.pyplot as plt

# Add project root to path for modules
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, project_root)

from modules.plotting import paper_style
from modules.figure_data import load_figure_data


# markdown figure description:
""" 
![Figure 1: Boundary Suppression as Thermodynamic Friction. (a) The suppressing agent's net payoff $\Pi_{\text{suppress}}$ versus total suppression effort $\delta^{\text{off}} + \delta^{\text{def}}$. The net payoff is initially positive (suppression captures some contested resource value) but crosses zero at $\delta_{\text{total}} = 1/\kappa = 0.50$ (profit erasure), after which every additional unit of suppression effort yields a net loss. The dashed line marks the cooperative payoff; suppression never exceeds cooperation even at its most profitable. (b) System dissipation $L^{(2)}_{\text{sys}}$ (total energy destroyed, red) and net system value $V_{\text{net}}$ (blue) versus suppression effort. The system becomes net-negative ($V_{\text{net}} < 0$) at $\delta = 0.333$, corresponding to $\Phi = 2$ ({prf:ref}`thm-net-negative-conflict`): the total energy dissipated by suppression exceeds the value of the contested resource. (c) N-group cascade: net system value versus the number of suppressed groups $N$ at four friction multiplier levels $\Phi \in \{1.5, 2.0, 2.8, 4.0\}$. For $\Phi \geq 2$, the system is net-negative at $N = 2$ and the net value decreases rapidly with each additional suppressed group, formalizing the cascading friction mechanism ({prf:ref}`thm-cascading-friction`).](output/figures/fig_adversarial_friction.png)
"""

# ---------------------------------------------------------------------------
# Load verified data
# ---------------------------------------------------------------------------
data = load_figure_data("adversarial_friction")

delta_total = data["delta_total"]
Pi_hack = data["Pi_hack"]
L_system = data["L_system"]
V_net = data["V_net"]
coop_payoff = float(data["coop_payoff"])
delta_sys_crossover = float(data["delta_sys_crossover"])
delta_indiv_crossover = float(data["delta_indiv_crossover"])
E_j = float(data["E_j"])
kappa = float(data["kappa"])
N_range = data["N_range"]
Phi_examples = data["Phi_examples"]
V_net_by_phi = data["V_net_by_phi"]
d_example = float(data["d_example"])
pi_example = float(data["pi_example"])
V_example_phi28_N2 = float(data["V_example_phi28_N2"])

# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------
paper_style()

fig, axes = plt.subplots(1, 3, figsize=(17, 5.5))

# --- Panel (a): Regime Net Payoff vs. Suppression Effort ---
ax = axes[0]
ax.plot(delta_total, Pi_hack, color="#2563EB", linewidth=2.2,
        label=r"Regime net payoff $\Pi_{\mathrm{suppress}}$")
ax.axhline(0, color="black", linewidth=0.8, linestyle="-")
ax.axhline(coop_payoff, color="#059669", linewidth=1.5, linestyle="--",
           label=f"Cooperative payoff = {coop_payoff:.0f}")
ax.axvline(delta_indiv_crossover, color="#DC2626", linewidth=1.2, linestyle=":",
           alpha=0.8)
ax.fill_between(delta_total, Pi_hack, 0,
                where=(Pi_hack < 0), alpha=0.12, color="#DC2626")
ax.annotate(
    f"Profit erasure\n$\\delta_{{\\mathrm{{total}}}} = 1/\\kappa = {delta_indiv_crossover:.2f}$",
    xy=(delta_indiv_crossover, 0),
    xytext=(delta_indiv_crossover - 0.3, -20),
    fontsize=9.5,
    arrowprops=dict(arrowstyle="->", color="#DC2626", lw=1.2),
    color="#DC2626",
)

# Annotate worked example
ax.plot(d_example, pi_example, "o", color="#DC2626", markersize=8, zorder=5)
ax.annotate(
    f"Worked example\n$\\delta = {d_example}$, $\\Pi = {pi_example:.0f}$",
    xy=(d_example, pi_example),
    xytext=(d_example + 0.025, 10),
    fontsize=9,
    arrowprops=dict(arrowstyle="->", color="#DC2626", lw=1),
    color="#DC2626",
)

ax.set_xlabel(r"Suppression effort $\delta^{\mathrm{off}} + \delta^{\mathrm{def}}$")
ax.set_ylabel("Energy units")
ax.set_title("(a) Regime Net Payoff\nvs. Suppression Effort")
ax.legend(fontsize=9, loc="upper right")
ax.grid(True, alpha=0.3)
ax.set_xlim(0, 1)

# --- Panel (b): System Dissipation vs. Damage ---
ax = axes[1]
ax.plot(delta_total, L_system, color="#DC2626", linewidth=2.2,
        label=r"System loss $L^{(2)}_{\mathrm{sys}}$")
ax.plot(delta_total, V_net, color="#2563EB", linewidth=2.2,
        label=r"Net value $V_{\mathrm{net}}$")
ax.axhline(0, color="black", linewidth=0.8, linestyle="-")
ax.axhline(E_j, color="gray", linewidth=1, linestyle="--", alpha=0.5,
           label=f"$E_j$ = {E_j:.0f}")
ax.axvline(delta_sys_crossover, color="#7C3AED", linewidth=1.2, linestyle=":",
           alpha=0.8)
ax.fill_between(delta_total, V_net, 0,
                where=(V_net < 0), alpha=0.10, color="#DC2626")
ax.annotate(
    f"System net-negative\n$\\delta = {delta_sys_crossover:.3f}$\n($\\Phi = 2$)",
    xy=(delta_sys_crossover, 0),
    xytext=(delta_sys_crossover + 0.12, 40),
    fontsize=9.5,
    arrowprops=dict(arrowstyle="->", color="#7C3AED", lw=1.2),
    color="#7C3AED",
)
ax.set_xlabel(r"Suppression effort $\delta^{\mathrm{off}} + \delta^{\mathrm{def}}$")
ax.set_ylabel("Energy units")
ax.set_title("(b) System Dissipation\nvs. Suppression Effort")
ax.legend(fontsize=9, loc="upper left")
ax.grid(True, alpha=0.3)
ax.set_xlim(0, 1)

# --- Panel (c): Critical Agent Count N*(Φ) ---
ax = axes[2]
Phi_range = np.linspace(1.01, 3.0, 500)
N_star = Phi_range / (Phi_range - 1)

ax.plot(Phi_range, N_star, color="#2563EB", linewidth=2.5)
ax.fill_between(Phi_range, N_star, 0, alpha=0.08, color="#2563EB")

# Shade net-negative region (above the curve)
ax.fill_between(Phi_range, N_star, 60, alpha=0.08, color="#DC2626")
ax.text(1.5, 25, "Net-negative\n(conflict destroys\nmore than resource)",
        fontsize=8, color="#DC2626", ha="center", style="italic")
ax.text(1.3, 1.4, "Net-positive", fontsize=8, color="#2563EB",
        ha="center", style="italic")

# Mark the paper's worked example: Φ = 2.2
phi_ex = 2.2
n_star_ex = phi_ex / (phi_ex - 1)
ax.plot(phi_ex, n_star_ex, "o", color="#DC2626", markersize=8, zorder=5)
ax.annotate(
    f"Worked example\n$\\Phi = {phi_ex}$, $N^* = {n_star_ex:.1f}$",
    xy=(phi_ex, n_star_ex),
    xytext=(2.1, 8),
    fontsize=9,
    arrowprops=dict(arrowstyle="->", color="#DC2626", lw=1),
    color="#DC2626",
)

# Mark the Φ = 2 threshold
ax.axvline(x=2.0, color="gray", linewidth=0.8, linestyle="--", alpha=0.6)
ax.text(2.03, 35, r"$\Phi = 2$", fontsize=8, color="gray")

ax.set_xlabel(r"Friction multiplier $\Phi$")
ax.set_ylabel(r"Critical agent count $N^* = \Phi / (\Phi - 1)$")
ax.set_title("(c) Break-Even Agent Count\nvs. Friction Multiplier")
ax.grid(True, alpha=0.3)
ax.set_xlim(1.0, 3.0)
ax.set_ylim(0, 40)

plt.tight_layout()

# Save
out_dir = os.path.join(project_root, "output", "figures")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "fig_adversarial_friction.png")
plt.savefig(out_path, dpi=300, bbox_inches="tight")
print(f"Figure saved to: {out_path}")
plt.close()
