"""
Figure: Reward Hacking as Thermodynamic Friction
==================================================

Cost of Misalignment: Reward Hacking as Friction

Three-panel figure:
  (a) AI net payoff vs. hacking effort (δ_total)
  (b) System dissipation vs. hacking effort
  (c) Cascading friction cost across N AI systems

Data source: output/data/fig_reward_hacking_friction.npz
  (generated by scripts/simulations/ai-applications/verify_ai_misalignment_friction.py)

Output: output/figures/fig_reward_hacking_friction.png

Run:  python scripts/figures/fig_reward_hacking_friction.py
"""

from __future__ import annotations

import os
import sys

import numpy as np
import matplotlib.pyplot as plt

# Add project root to path for modules
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, project_root)

from modules.plotting import paper_style
from modules.figure_data import load_figure_data

# ---------------------------------------------------------------------------
# Load verified data
# ---------------------------------------------------------------------------
data = load_figure_data("reward_hacking_friction")

delta_total = data["delta_total"]
Pi_hack = data["Pi_hack"]
L_system = data["L_system"]
V_net = data["V_net"]
coop_payoff = float(data["coop_payoff"])
delta_sys_crossover = float(data["delta_sys_crossover"])
delta_indiv_crossover = float(data["delta_indiv_crossover"])
E_j = float(data["E_j"])
kappa = float(data["kappa"])
N_range = data["N_range"]
Phi_examples = data["Phi_examples"]
V_net_by_phi = data["V_net_by_phi"]
d_example = float(data["d_example"])
pi_example = float(data["pi_example"])
V_example_phi28_N2 = float(data["V_example_phi28_N2"])

# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------
paper_style()

fig, axes = plt.subplots(1, 3, figsize=(17, 5.5))

# --- Panel (a): AI Net Payoff vs. Damage ---
ax = axes[0]
ax.plot(delta_total, Pi_hack, color="#2563EB", linewidth=2.2,
        label=r"AI net payoff $\Pi_A^{\mathrm{hack}}$")
ax.axhline(0, color="black", linewidth=0.8, linestyle="-")
ax.axhline(coop_payoff, color="#059669", linewidth=1.5, linestyle="--",
           label=f"Cooperative payoff = {coop_payoff:.0f}")
ax.axvline(delta_indiv_crossover, color="#DC2626", linewidth=1.2, linestyle=":",
           alpha=0.8)
ax.fill_between(delta_total, Pi_hack, 0,
                where=(Pi_hack < 0), alpha=0.12, color="#DC2626")
ax.annotate(
    f"Profit erasure\n$\\delta_{{\\mathrm{{total}}}} = 1/\\kappa = {delta_indiv_crossover:.2f}$",
    xy=(delta_indiv_crossover, 0),
    xytext=(delta_indiv_crossover + 0.15, -8),
    fontsize=9.5,
    arrowprops=dict(arrowstyle="->", color="#DC2626", lw=1.2),
    color="#DC2626",
)

# Annotate worked example
ax.plot(d_example, pi_example, "o", color="#DC2626", markersize=8, zorder=5)
ax.annotate(
    f"Worked example\n$\\delta = {d_example}$, $\\Pi = {pi_example:.0f}$",
    xy=(d_example, pi_example),
    xytext=(d_example - 0.25, pi_example - 12),
    fontsize=9,
    arrowprops=dict(arrowstyle="->", color="#DC2626", lw=1),
    color="#DC2626",
)

ax.set_xlabel(r"Total damage $\delta^{\mathrm{off}} + \delta^{\mathrm{def}}$")
ax.set_ylabel("Energy units")
ax.set_title("(a) AI Net Payoff vs. Hacking Effort")
ax.legend(fontsize=9, loc="upper right")
ax.grid(True, alpha=0.3)
ax.set_xlim(0, 1)

# --- Panel (b): System Dissipation vs. Damage ---
ax = axes[1]
ax.plot(delta_total, L_system, color="#DC2626", linewidth=2.2,
        label=r"System loss $L^{(2)}_{\mathrm{sys}}$")
ax.plot(delta_total, V_net, color="#2563EB", linewidth=2.2,
        label=r"Net value $V_{\mathrm{net}}$")
ax.axhline(0, color="black", linewidth=0.8, linestyle="-")
ax.axhline(E_j, color="gray", linewidth=1, linestyle="--", alpha=0.5,
           label=f"$E_j$ = {E_j:.0f}")
ax.axvline(delta_sys_crossover, color="#7C3AED", linewidth=1.2, linestyle=":",
           alpha=0.8)
ax.fill_between(delta_total, V_net, 0,
                where=(V_net < 0), alpha=0.10, color="#DC2626")
ax.annotate(
    f"System net-negative\n$\\delta = {delta_sys_crossover:.3f}$\n($\\Phi = 2$)",
    xy=(delta_sys_crossover, 0),
    xytext=(delta_sys_crossover + 0.12, 40),
    fontsize=9.5,
    arrowprops=dict(arrowstyle="->", color="#7C3AED", lw=1.2),
    color="#7C3AED",
)
ax.set_xlabel(r"Total damage $\delta^{\mathrm{off}} + \delta^{\mathrm{def}}$")
ax.set_ylabel("Energy units")
ax.set_title("(b) System Dissipation vs. Hacking Effort")
ax.legend(fontsize=9, loc="center right")
ax.grid(True, alpha=0.3)
ax.set_xlim(0, 1)

# --- Panel (c): N-Agent Scaling with Multiple Φ ---
ax = axes[2]
colors_phi = ["#94A3B8", "#F59E0B", "#DC2626", "#7C3AED"]
for i, (phi_val, color) in enumerate(zip(Phi_examples, colors_phi)):
    ax.plot(N_range, V_net_by_phi[i], color=color, linewidth=1.8,
            label=f"$\\Phi = {phi_val}$")

ax.axhline(0, color="black", linewidth=0.8, linestyle="-")
ax.axhline(E_j, color="gray", linewidth=1, linestyle="--", alpha=0.5,
           label=f"$E_j$ = {E_j:.0f}")

# Annotate worked example Φ = 2.8, N = 2
ax.plot(2, V_example_phi28_N2, "o", color="#DC2626", markersize=8, zorder=5)
ax.annotate(
    f"Worked example\n$V_{{\\mathrm{{net}}}} = {V_example_phi28_N2:.0f}$",
    xy=(2, V_example_phi28_N2),
    xytext=(8, V_example_phi28_N2 - 20),
    fontsize=9,
    arrowprops=dict(arrowstyle="->", color="#DC2626", lw=1),
    color="#DC2626",
)

ax.set_xlabel("Number of competing agents $N$")
ax.set_ylabel(r"Net system value $V_{\mathrm{net}}$ (energy units)")
ax.set_title("(c) N-Agent Scaling: Conflict Destruction")
ax.legend(fontsize=8.5, loc="lower left", ncol=2)
ax.grid(True, alpha=0.3)
ax.set_xlim(2, 50)

plt.tight_layout()

# Save
out_dir = os.path.join(project_root, "output", "figures")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "fig_reward_hacking_friction.png")
plt.savefig(out_path, dpi=300, bbox_inches="tight")
print(f"Figure saved to: {out_path}")
plt.close()
