"""
Figure: Deceptive Alignment as Entropy Injection
==================================================

Two-panel figure:
  (a) Verification cost ρ(q) vs deception rate q
  (b) Network collapse threshold q*(d) vs network depth d

Data source: output/data/fig_deceptive_alignment_entropy.npz
  (generated by scripts/simulations/ai-applications/verify_ai_deception_entropy.py)

Output: output/figures/fig_deceptive_alignment_entropy.png

Run:  python scripts/figures/fig_deceptive_alignment_entropy.py
"""

from __future__ import annotations

import sys
import os

import numpy as np
import matplotlib.pyplot as plt

# Add project root for shared plotting utilities
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from modules.plotting import paper_style
from modules.figure_data import load_figure_data

paper_style()

# ---------------------------------------------------------------------------
# Load verified data
# ---------------------------------------------------------------------------
data = load_figure_data("deceptive_alignment_entropy")

q_range = data["q_range"]
rho_vals = data["rho_vals"]
verify_overhead = data["verify_overhead_vals"]
q_markers = data["q_markers"]
rho_at_markers = data["rho_at_markers"]
d_range = data["d_range"]
q_stars = data["q_stars_005"]
q_stars_10 = data["q_stars_010"]

# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5.5))

# --- Panel (a) ---
color_rho = "#1f77b4"

ax1.semilogy(q_range, rho_vals, color=color_rho, linewidth=2.2,
             label=r"Redundancy factor $\rho(q) = 1/C(q)$")
ax1.semilogy(q_range, verify_overhead, color="#ff7f0e", linewidth=2.0,
             linestyle="--",
             label=r"Verification overhead $h(q)/(1{-}h(q))$")

# Mark key points
for qm, rv in zip(q_markers, rho_at_markers):
    ax1.plot(qm, rv, "o", color=color_rho, markersize=7, zorder=5)
    ax1.annotate(f"$q={qm}$\n$\\rho={rv:.1f}$",
                 xy=(qm, rv), xytext=(8, 10),
                 textcoords="offset points", fontsize=9,
                 ha="left", va="bottom",
                 bbox=dict(boxstyle="round,pad=0.2", fc="white",
                           ec="gray", alpha=0.8))

ax1.axhline(y=1, color="gray", linestyle=":", linewidth=0.8, alpha=0.5)
ax1.set_xlabel("Deception rate $q$")
ax1.set_ylabel("Factor (log scale)")
ax1.set_title("(a) Verification cost vs. deception rate")
ax1.set_xlim(0, 0.50)
ax1.set_ylim(0.8, 200)
ax1.legend(loc="upper left", fontsize=10)
ax1.grid(True, alpha=0.3, which="both")

# --- Panel (b): Network collapse threshold q*(d) ---
ax2.plot(d_range, q_stars, "s-", color="#2ca02c", linewidth=2.2,
         markersize=7, label=r"$q^*(d)$ at $C_{\rm eff} = 0.05$")
ax2.plot(d_range, q_stars_10, "^--", color="#9467bd", linewidth=1.8,
         markersize=6, label=r"$q^*(d)$ at $C_{\rm eff} = 0.10$")

# Mark specific depths
for d_mark in [1, 2, 3, 5, 10]:
    idx = d_mark - 1
    qs = q_stars[idx]
    ax2.annotate(f"$d={d_mark}$\n$q^*={qs:.3f}$",
                 xy=(d_mark, qs), xytext=(-5, -20),
                 textcoords="offset points", fontsize=8.5,
                 ha="center", va="top",
                 bbox=dict(boxstyle="round,pad=0.2", fc="white",
                           ec="gray", alpha=0.8))

# Shade zones
ax2.fill_between(d_range, q_stars, 0.5,
                 alpha=0.12, color="#d62728",
                 label="Network collapse zone")
ax2.fill_between(d_range, 0, q_stars,
                 alpha=0.08, color="#2ca02c",
                 label="Viable communication zone")

ax2.set_xlabel("Network depth $d$ (cascaded BSC layers)")
ax2.set_ylabel("Critical deception rate $q^*$")
ax2.set_title(r"(b) Collapse threshold $q^*(d)$ vs. network depth")
ax2.set_xlim(1, 20)
ax2.set_ylim(0, 0.50)
ax2.legend(loc="upper right", fontsize=9)
ax2.grid(True, alpha=0.3)

fig.suptitle("Deceptive Alignment as Entropy Injection",
             fontsize=14, fontweight="bold", y=1.02)
plt.tight_layout()

# Save
out_dir = os.path.join(os.path.dirname(__file__), "..", "..", "output", "figures")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "fig_deceptive_alignment_entropy.png")
fig.savefig(out_path, dpi=300, bbox_inches='tight')
print(f"Saved: {out_path}")
plt.close(fig)
