"""
Figure: Disinformation as Entropy Injection
=============================================

Two-panel figure:
  (a) Verification cost ρ(q) vs disinformation rate q
  (b) Network collapse threshold q*(d) vs information cascade depth d

Data source: output/data/fig_deception_entropy.npz
  (generated by scripts/simulations/applied/verify_deception_entropy.py)

Output: output/figures/fig_deception_entropy.png

Run:  python scripts/figures/fig_deception_entropy.py
"""

from __future__ import annotations

import sys
import os

import numpy as np
import matplotlib.pyplot as plt

# Add project root for shared plotting utilities
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from modules.plotting import paper_style
from modules.figure_data import load_figure_data

# markdown figure description:
""" 
![Figure 1: Disinformation as Entropy Injection. (a) Fact-checking cost versus disinformation rate $q$, showing the redundancy factor $\rho(q) = 1/C(q)$ (the number of independent sources required to extract one reliable bit) and the verification overhead $h(q)/(1-h(q))$. At $q = 0.25$, an agent must consult 5.3 independent sources per decision; by $q = 0.4$, the redundancy factor exceeds 34, consistent with the superlinear decision-cost scaling proved in {prf:ref}`thm-decision-cost-quadratic`. (b) The critical disinformation rate $q^*(d)$ at which informed decision-making collapses, as a function of information cascade depth $d$ (the number of layers through which a signal passes before reaching the decision-maker). At depth $d = 1$ (direct observation), the system tolerates $q^* = 0.369$; by $d = 5$ (a five-layer sharing cascade, typical of social media propagation), the threshold drops to $q^* = 0.118$; at $d = 10$, it falls to $q^* = 0.063$. The red zone marks conditions under which the effective channel capacity collapses below the threshold for informed decision-making ({prf:ref}`thm-systemic-deception`).](output/figures/fig_deception_entropy.png)

"""

paper_style()

# ---------------------------------------------------------------------------
# Load verified data
# ---------------------------------------------------------------------------
data = load_figure_data("deception_entropy")

q_range = data["q_range"]
rho_vals = data["rho_vals"]
verify_overhead = data["verify_overhead_vals"]
q_markers = data["q_markers"]
rho_at_markers = data["rho_at_markers"]
d_range = data["d_range"]
q_stars = data["q_stars_005"]
q_stars_10 = data["q_stars_010"]

# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5.5))

# --- Panel (a) ---
color_rho = "#1f77b4"

ax1.semilogy(q_range, rho_vals, color=color_rho, linewidth=2.2,
             label=r"Fact-checking redundancy $\rho(q) = 1/C(q)$")
ax1.semilogy(q_range, verify_overhead, color="#ff7f0e", linewidth=2.0,
             linestyle="--",
             label=r"Verification overhead $h(q)/(1{-}h(q))$")

# Mark key points — offset labels to avoid line overlap
_offsets = {0.05: (-25, 50), 0.1: (0, 55), 0.25: (-45, 30), 0.4: (-70, 12)}
for qm, rv in zip(q_markers, rho_at_markers):
    ax1.plot(qm, rv, "o", color=color_rho, markersize=7, zorder=5)
    ox, oy = _offsets.get(float(qm), (8, 10))
    ax1.annotate(f"$q={qm}$\n$\\rho={rv:.1f}$",
                 xy=(qm, rv), xytext=(ox, oy),
                 textcoords="offset points", fontsize=9,
                 ha="left", va="bottom",
                 bbox=dict(boxstyle="round,pad=0.2", fc="white",
                           ec="gray", alpha=0.8),
                 arrowprops=dict(arrowstyle="->", color="gray", lw=0.8))

ax1.axhline(y=1, color="gray", linestyle=":", linewidth=0.8, alpha=0.5)
ax1.set_xlabel("Disinformation rate $q$")
ax1.set_ylabel("Factor (log scale)")
ax1.set_title("(a) Fact-checking cost vs.\ndisinformation rate")
ax1.set_xlim(0, 0.50)
ax1.set_ylim(0.8, 200)
ax1.legend(loc="upper left", fontsize=10)
ax1.grid(True, alpha=0.3, which="both")

# --- Panel (b): Network collapse threshold q*(d) ---
ax2.plot(d_range, q_stars, "s-", color="#2ca02c", linewidth=2.2,
         markersize=7, label=r"$q^*(d)$ at $C_{\rm eff} = 0.05$")
ax2.plot(d_range, q_stars_10, "^--", color="#9467bd", linewidth=1.8,
         markersize=6, label=r"$q^*(d)$ at $C_{\rm eff} = 0.10$")

# Mark specific depths — alternate above/below to avoid overlap
_depth_offsets = {1: (25, 25), 2: (25, 40), 3: (15, 25), 5: (15, 25), 10: (-10, 25)}
for d_mark in [1, 2, 3, 5, 10]:
    idx = d_mark - 1
    qs = q_stars[idx]
    ox, oy = _depth_offsets[d_mark]
    va = "bottom" if oy > 0 else "top"
    ax2.annotate(f"$d={d_mark}$, $q^*={qs:.3f}$",
                 xy=(d_mark, qs), xytext=(ox, oy),
                 textcoords="offset points", fontsize=8,
                 ha="left", va=va,
                 bbox=dict(boxstyle="round,pad=0.2", fc="white",
                           ec="gray", alpha=0.8),
                 arrowprops=dict(arrowstyle="->", color="gray", lw=0.8))

# Shade zones
ax2.fill_between(d_range, q_stars, 0.5,
                 alpha=0.12, color="#d62728",
                 label="Decision collapse zone")
ax2.fill_between(d_range, 0, q_stars,
                 alpha=0.08, color="#2ca02c",
                 label="Informed decision zone")

ax2.set_xlabel("Information cascade depth $d$ (layers of sharing)")
ax2.set_ylabel("Critical disinformation rate $q^*$")
ax2.set_title(r"(b) Collapse threshold $q^*(d)$" + "\nvs. cascade depth")
ax2.set_xlim(1, 20)
ax2.set_ylim(0, 0.50)
ax2.legend(loc="upper right", fontsize=9)
ax2.grid(True, alpha=0.3)

fig.suptitle("Disinformation as Entropy Injection",
             fontsize=14, fontweight="bold", y=1.02)
plt.tight_layout()

# Save
out_dir = os.path.join(os.path.dirname(__file__), "..", "..", "output", "figures")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "fig_deception_entropy.png")
fig.savefig(out_path, dpi=300, bbox_inches='tight')
print(f"Saved: {out_path}")
plt.close(fig)
