"""
Figure: Monocentric Institutional Collapse — Cascade Dynamics
==============================================================

Three-panel figure:
  (a) Coexistence potential V(r) for M = 10^2, 10^4, 10^6, 10^8
  (b) Phase diagram: band width w as function of M and Bi,
      with irreversible collapse zone shaded
  (c) Cascade dynamics: surviving independent entities vs. time
      — three scenarios (no failure, single-channel shock, dual-channel)

Data source: output/data/fig_institutional_collapse.npz
  (generated by scripts/simulations/applied/verify_institutional_collapse.py)

Output: output/figures/fig_institutional_collapse.png
"""

from __future__ import annotations

import sys
import os

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from modules.plotting import paper_style
from modules.figure_data import load_figure_data

# markdown figure description:
""" 
![Figure 1: Monocentric Institutional Collapse. (a) The coexistence potential $V(r)/D$ for centers of increasing institutional mass $\mathcal{M} \in \{10^2, 10^4, 10^6, 10^8\}$ ({prf:ref}`def-coexistence-potential`). All curves share the same attractor location $r^* = 2\tau/G = 1.0$ but differ in well depth: larger institutions create deeper potential wells and wider coexistence bands (shaded region where $V(r) < 0$). (b) Phase diagram of freedom bandwidth $w$ versus institutional mass $\mathcal{M}$ for agents of varying complexity $B_i \in \{10, 25, 50, 100, 200\}$ ({prf:ref}`thm-freedom-bandwidth`). All curves follow $w \propto \mathcal{M}$ in the large-mass limit; higher-complexity agents (larger $B_i$) require more massive institutions to achieve the same bandwidth and face a higher minimum viable institutional mass $\mathcal{M}_{\min}$ ({prf:ref}`thm-existence-coexistence-band`). The shaded region marks the irreversible collapse zone where institutional concentration exceeds the critical threshold. (c) Institutional cascade dynamics: surviving independent entities versus time under three scenarios, illustrating {prf:ref}`cor-cascade-collapse`. Under no failure (green), all entities survive. A single-channel shock (orange, $t = 5$) produces a small, contained reduction. A dual-channel shock (red, $t = 5$ followed by critical threshold breach at $t = 10$) triggers catastrophic cascade collapse, reducing surviving entities from 50 to near zero.](output/figures/fig_institutional_collapse.png)
"""

paper_style()

# ---------------------------------------------------------------------------
# Load verified data
# ---------------------------------------------------------------------------
data = load_figure_data("institutional_collapse")

r_arr = data["r_arr"]
masses = data["masses"]
V_curves = data["V_curves"]
V_star_vals = data["V_star_vals"]
r_star = float(data["r_star"])
M_range = data["M_range"]
Bi_values = data["Bi_values"]
bandwidth_curves = data["bandwidth_curves"]
M_min_vals = data["M_min_vals"]
times = data["times"]
surviving_all = data["surviving_all"] # shape (3, len(times)) for 3 scenarios
G = float(data["G"])
gamma = float(data["gamma"])
Bi = float(data["Bi"])
M_crit = float(data["M_crit"])

# ---------------------------------------------------------------------------
# Create figure
# ---------------------------------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(15, 4.8))

# ---------------------------------------------------------------------------
# Panel (a): V(r) for different M values
# ---------------------------------------------------------------------------
ax = axes[0]
colors = ["#d62728", "#ff7f0e", "#2ca02c", "#1f77b4"]
labels = [rf"$\mathcal{{M}} = 10^{int(np.log10(m))}$" for m in masses]

for i, (color, label) in enumerate(zip(colors, labels)):
    V_arr = V_curves[i]
    V_star_val = V_star_vals[i]
    V_norm = V_arr / abs(V_star_val) if abs(V_star_val) > 0 else V_arr
    ax.plot(r_arr, V_norm, color=color, linewidth=1.8, label=label)

ax.axhline(0, color="gray", linewidth=0.5, linestyle="--")
ax.axvline(r_star, color="gray", linewidth=0.5, linestyle=":",
           label=rf"$r^* = {r_star:.1f}$")
ax.set_xlabel(r"Coupling distance $r$")
ax.set_ylabel(r"$V(r)\,/\,D$")
ax.set_title("(a) Coexistence Potential")
ax.set_ylim(-1.5, 1.5)
ax.legend(fontsize=8, loc="upper right")

# Shade coexistence band for largest M (normalised)
V_shade = V_curves[-1] / abs(V_star_vals[-1])
ax.fill_between(r_arr, V_shade, 0,
                where=(V_shade < 0), alpha=0.1, color="#1f77b4")

# ---------------------------------------------------------------------------
# Panel (b): Phase diagram — bandwidth w vs M for different Bi
# ---------------------------------------------------------------------------
ax = axes[1]
colors_b = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"]

for i, (Bi_val, color) in enumerate(zip(Bi_values, colors_b)):
    ax.loglog(M_range, bandwidth_curves[i], color=color, linewidth=1.5,
              label=fr"$B_i = {int(Bi_val)}$")
    Mm = M_min_vals[i]
    if M_range[0] <= Mm <= M_range[-1]:
        ax.plot(Mm, 0.1, marker="v", color=color, markersize=6, zorder=5)

# Irreversible collapse zone
ax.axvspan(M_crit, M_range[-1], alpha=0.08, color="red", zorder=0)
ax.text(5e7, 5e1, r"$\alpha > \alpha^*$" + "\n(irreversible\ncollapse zone)",
        fontsize=8, color="#d62728", ha="center", va="bottom", style="italic")

ax.set_xlabel(r"Institutional mass $\mathcal{M}$")
ax.set_ylabel(r"Freedom bandwidth $w$")
ax.set_title(r"(b) Phase Diagram: $w$ vs $\mathcal{M}$")
ax.legend(fontsize=8, loc="upper left")
ax.set_xlim(M_range[0], M_range[-1])
ax.set_ylim(1e-1, 1e9)

# Diagonal reference line
M_ref = np.array([1e4, 1e9])
w_ref = G * M_ref / (gamma * Bi)
ax.plot(M_ref, w_ref, "k--", linewidth=0.7, alpha=0.5)
ax.annotate(r"$w \propto \mathcal{M}$", xy=(4e5, 1e0), fontsize=10,
            color="#444444", fontweight="bold")

# ---------------------------------------------------------------------------
# Panel (c): Dual-channel cascade simulation
# ---------------------------------------------------------------------------
ax = axes[2]

scenario_meta = [
    {"name": "No failure", "color": "#2ca02c", "ls": "-"},
    {"name": r"Key institution weakened ($t{=}5$)", "color": "#ff7f0e", "ls": "--"},
    {"name": r"Dual-channel shock ($t{=}5$, $\alpha{>}\alpha^*$ at $t{=}10$)",
     "color": "#d62728", "ls": "-."},
]

for i, meta in enumerate(scenario_meta):
    ax.plot(times, surviving_all[i], color=meta["color"],
            linewidth=1.8, linestyle=meta["ls"], label=meta["name"])

ax.axvline(5, color="gray", linewidth=0.5, linestyle=":", alpha=0.5)
ax.axvline(10, color="gray", linewidth=0.5, linestyle=":", alpha=0.5)
ax.annotate("Institution\nweakened", xy=(5, 5), fontsize=7, color="gray",
            ha="center", va="bottom")
ax.annotate(r"$\alpha > \alpha^*$", xy=(10, 5), fontsize=7, color="#d62728",
            ha="center", va="bottom", fontweight="bold")

ax.set_xlabel("Time")
ax.set_ylabel("Surviving independent entities")
ax.set_title("(c) Institutional Cascade Dynamics")
ax.set_ylim(0, 62)
ax.legend(fontsize=7, loc="upper left")

# ---------------------------------------------------------------------------
# Save
# ---------------------------------------------------------------------------
plt.tight_layout()
out_dir = os.path.join(os.path.dirname(__file__), "..", "..", "output", "figures")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "fig_institutional_collapse.png")
plt.savefig(out_path, dpi=300, bbox_inches="tight")
print(f"Figure saved to {out_path}")
plt.close()
