"""
Figure: The Burning-Library Inequality (Biosphere Preservation)
================================================================

Three-panel figure:
  (a) Log-scale bar chart: extraction value vs. rebuild cost vs. search cost
      across biosphere, ecosystem, and species scales
  (b) Burning-Library ratio R_BL vs. ordering efficiency η_order (sensitivity)
  (c) Present value of generative information vs. discount rate δ

Data source: output/data/fig_burning_library.npz
  (generated by scripts/simulations/applications/verify_biosphere_preservation.py)

Output: output/figures/fig_burning_library.png

Run:  python scripts/figures/fig_burning_library.py
"""

from __future__ import annotations

import sys
import os

import numpy as np
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
from modules.plotting import paper_style
from modules.figure_data import load_figure_data

paper_style()

# ---------------------------------------------------------------------------
# Load verified data
# ---------------------------------------------------------------------------
data = load_figure_data("burning_library")

N_vals = data["N_vals"]
E_extract = data["E_extract"]
W_rebuild = data["W_rebuild"]
Xi_search = data["Xi_search"]
eta_range = data["eta_range"]
R_BL_vals = data["R_BL_vals"]
P_GPP = float(data["P_GPP"])
delta_range = data["delta_range"]
PV_gen = data["PV_gen"]
E_destroy = float(data["E_destroy"])
N_bio = float(data["N_bio"])
I_gen_rate = float(data["I_gen_rate"])
v_per_bit = float(data["v_per_bit"])

# ---------------------------------------------------------------------------
# Figure: 3 panels
# ---------------------------------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# ===== Panel (a): Log-scale bar chart across scales =====
ax = axes[0]

systems = ['Single\nSpecies', 'Coral\nReef', 'Amazon\nRainforest', "Earth's\nBiosphere"]
x = np.arange(len(systems))
width = 0.22

bars1 = ax.bar(x - width, np.log10(E_extract), width, color='#d62728',
               label='Extraction yield $E_{\\mathrm{destroy}}$', alpha=0.85)
bars2 = ax.bar(x, np.log10(W_rebuild), width, color='#2ca02c',
               label='Rebuild cost $W_{\\mathrm{rebuild}}$', alpha=0.85)
bars3 = ax.bar(x + width, np.log10(Xi_search), width, color='#1f77b4',
               label='Search cost $\\Xi \\cdot W_L$', alpha=0.85)

ax.set_xticks(x)
ax.set_xticklabels(systems, fontsize=9)
ax.set_ylabel('$\\log_{10}$ Energy (J)', fontsize=11)
ax.set_title('(a) Destruction Value vs.\nRebuild/Search Cost', fontsize=12)
ax.legend(fontsize=8, loc='upper left')
ax.grid(True, alpha=0.3, axis='y')
ax.set_ylim(5, 40)

ax.annotate('$\\mathcal{R}_{BL} = 10^{-7}$',
            xy=(3 - width, np.log10(E_extract[-1])),
            xytext=(2.2, 28),
            fontsize=9, fontweight='bold', color='#d62728',
            arrowprops=dict(arrowstyle='->', color='#d62728', lw=1.2))

# ===== Panel (b): R_BL vs. ordering efficiency =====
ax = axes[1]

ax.semilogy(eta_range * 100, R_BL_vals, color='#d62728', linewidth=2.5)
ax.axhline(y=1e-7, color='gray', ls='--', alpha=0.5, linewidth=1)
ax.axhline(y=1.0, color='black', ls='-', alpha=0.3, linewidth=1)
ax.text(4.5, 1.5, '$\\mathcal{R}_{BL} = 1$ (breakeven)', fontsize=8,
        ha='right', color='black', alpha=0.5)

ax.axvline(x=1.0, color='#2ca02c', ls='--', alpha=0.8, linewidth=1.5)
ax.text(1.15, 5e-8, 'Baseline\n$\\eta=1\\%$', fontsize=8, color='#2ca02c')

ax.fill_between(eta_range * 100, R_BL_vals, 1.0, alpha=0.1, color='#d62728')

ax.set_xlabel('Ordering Efficiency $\\eta_{\\mathrm{order}}$ (%)', fontsize=11)
ax.set_ylabel('Burning-Library Ratio $\\mathcal{R}_{BL}$', fontsize=11)
ax.set_title('(b) Sensitivity: $\\mathcal{R}_{BL}$ vs.\nOrdering Efficiency', fontsize=12)
ax.set_xlim(0.1, 5.0)
ax.set_ylim(1e-8, 1e1)
ax.grid(True, alpha=0.3)

ax.annotate('$\\mathcal{R}_{BL} \\ll 1$ for all\nplausible $\\eta$',
            xy=(0.3, R_BL_vals[-1]),
            xytext=(2.5, 1e-5),
            fontsize=9, fontstyle='italic',
            arrowprops=dict(arrowstyle='->', color='gray', lw=0.8))

# ===== Panel (c): PV of generative information vs. discount rate =====
ax = axes[2]

ax.loglog(delta_range, PV_gen, color='#1f77b4', linewidth=2.5,
          label='$PV_{\\mathrm{gen}} = \\dot{\\mathcal{I}}_{\\mathrm{gen}} \\cdot v / \\delta$')

ax.axhline(y=E_destroy, color='#d62728', ls='--', alpha=0.8, linewidth=1.5,
           label=f'$E_{{\\mathrm{{destroy}}}} = 10^{{{int(np.log10(E_destroy))}}}$ J')
ax.axhline(y=N_bio, color='#2ca02c', ls='--', alpha=0.8, linewidth=1.5,
           label=f'$\\mathcal{{N}}_{{\\mathrm{{bio}}}} \\sim 10^{{{int(round(np.log10(N_bio)))}}}$ J')

for delta_pt, lx, ly in [(0.05, 0.065, 3e16), (0.001, 0.0015, 3e18)]:
    pv_pt = I_gen_rate * v_per_bit / delta_pt
    ax.plot(delta_pt, pv_pt, 'ko', markersize=5, zorder=5)
    ax.annotate(f'$\\delta={delta_pt}$\n$PV={pv_pt:.0e}$ J',
                xy=(delta_pt, pv_pt), xytext=(lx, ly), fontsize=8,
                arrowprops=dict(arrowstyle='->', color='black', lw=0.8))

ax.set_xlabel('Discount Rate $\\delta$', fontsize=11)
ax.set_ylabel('Present Value (J)', fontsize=11)
ax.set_title('(c) Present Value of Generative\nInformation vs. Discount Rate', fontsize=12)
ax.set_xlim(1e-4, 1)
ax.set_ylim(1e14, 1e30)
ax.legend(fontsize=8, loc='upper right')
ax.grid(True, alpha=0.3)

delta_mask = delta_range[PV_gen > E_destroy]
pv_mask = PV_gen[PV_gen > E_destroy]
ax.fill_between(delta_mask, pv_mask, E_destroy, alpha=0.08, color='#1f77b4')

# ---------------------------------------------------------------------------
# Save
# ---------------------------------------------------------------------------
plt.tight_layout()
out_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'output', 'figures')
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, 'fig_burning_library.png')
plt.savefig(out_path, dpi=300, bbox_inches='tight')
print(f"Saved: {out_path}")
plt.close()
