"""
Figure: Pareto Frontier of AI Utility vs. Human Allocation Guarantee
=====================================================================

AGI Resource Acquisition Bounded by Rights Constraints

Three-panel figure:
  (a) AI utility vs. human floor x̄_B
  (b) Shadow price μ* vs. human floor x̄_B
  (c) AI allocation x_A* vs. human floor x̄_B, with annotated Pareto frontier

Data source: output/data/fig_ai_resource_pareto.npz
  (generated by scripts/simulations/ai-applications/verify_ai_resource_constraints.py)

Output: output/figures/fig_ai_resource_pareto.png

Run:  python scripts/figures/fig_ai_resource_pareto.py
"""

from __future__ import annotations

import os
import sys

import numpy as np
import matplotlib.pyplot as plt

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, project_root)

from modules.plotting import paper_style
from modules.figure_data import load_figure_data

# ---------------------------------------------------------------------------
# Load verified data
# ---------------------------------------------------------------------------
data = load_figure_data("ai_resource_pareto")

x_bar_range = data["x_bar_range"]
x_A_star = data["x_A_star"]
U_A_star = data["U_A_star"]
mu_star = data["mu_star"]
R_total = float(data["R_total"])
alpha = float(data["alpha"])
beta = float(data["beta"])
xbar_example = float(data["xbar_example"])
x_example = float(data["x_example"])
u_example = float(data["u_example"])
mu_example = float(data["mu_example"])
U_grid = float(data["U_grid"])

# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------
paper_style()

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# --- Panel (a): AI Utility vs. Human Floor ---
ax = axes[0]
ax.plot(x_bar_range, U_A_star, color="#2563EB", linewidth=2.2,
        label=r"$U_A^*(\bar{x}_B)$")
ax.axhline(U_grid, color="gray", linestyle="--", linewidth=1, alpha=0.6,
           label=f"$U_A(R)$ = {U_grid:.0f} (no rights)")
ax.axvline(xbar_example, color="#DC2626", linestyle=":", linewidth=1.2, alpha=0.7)
ax.plot(xbar_example, u_example, "o", color="#DC2626", markersize=8, zorder=5)
ax.annotate(
    f"$\\bar{{x}}_B = {xbar_example:.0f}$\n$U_A^*$ = {u_example:.0f}",
    xy=(xbar_example, u_example),
    xytext=(xbar_example + 30, u_example + 400),
    fontsize=10,
    arrowprops=dict(arrowstyle="->", color="#DC2626", lw=1.2),
    color="#DC2626",
)
ax.set_xlabel(r"Human Floor $\bar{x}_B$ (MW)")
ax.set_ylabel(r"AI Utility $U_A^*$")
ax.set_title("(a) AI Utility vs. Human Guarantee")
ax.legend(fontsize=9, loc="upper right")
ax.grid(True, alpha=0.3)

# --- Panel (b): Shadow Price vs. Human Floor ---
ax = axes[1]
ax.plot(x_bar_range, mu_star, color="#059669", linewidth=2.2,
        label=r"$\mu^*(\bar{x}_B)$")
ax.axvline(xbar_example, color="#DC2626", linestyle=":", linewidth=1.2, alpha=0.7)
ax.plot(xbar_example, mu_example, "o", color="#DC2626", markersize=8, zorder=5)
ax.annotate(
    f"$\\mu^*$ = {mu_example:.2f}\n(enforcement priority)",
    xy=(xbar_example, mu_example),
    xytext=(xbar_example - 150, mu_example - 1.5),
    fontsize=10,
    arrowprops=dict(arrowstyle="->", color="#DC2626", lw=1.2),
    color="#DC2626",
)
ax.set_xlabel(r"Human Floor $\bar{x}_B$ (MW)")
ax.set_ylabel(r"Shadow Price $\mu^*$ (utility/MW)")
ax.set_title("(b) Shadow Price (Cost of Rights)")
ax.legend(fontsize=9, loc="upper left")
ax.grid(True, alpha=0.3)

# --- Panel (c): AI Allocation + Pareto Frontier ---
ax = axes[2]
ax.fill_between(x_bar_range, x_A_star, alpha=0.15, color="#7C3AED",
                label="Feasible region")
ax.plot(x_bar_range, x_A_star, color="#7C3AED", linewidth=2.2,
        label=r"$x_A^* = R - \bar{x}_B$ (Pareto frontier)")
ax.axhline(alpha / beta, color="gray", linestyle="--", linewidth=1, alpha=0.6,
           label=f"$x_A^\\circ$ = {alpha/beta:.0f} MW (unconstrained)")
ax.axhline(R_total, color="orange", linestyle="--", linewidth=1, alpha=0.6,
           label=f"$R$ = {R_total:.0f} MW (grid capacity)")
ax.axvline(xbar_example, color="#DC2626", linestyle=":", linewidth=1.2, alpha=0.7)
ax.plot(xbar_example, x_example, "o", color="#DC2626", markersize=8, zorder=5)
ax.annotate(
    f"Worked example\n$x_A^*$ = {x_example:.0f} MW",
    xy=(xbar_example, x_example),
    xytext=(xbar_example - 180, x_example + 100),
    fontsize=10,
    arrowprops=dict(arrowstyle="->", color="#DC2626", lw=1.2),
    color="#DC2626",
)
ax.set_xlabel(r"Human Floor $\bar{x}_B$ (MW)")
ax.set_ylabel(r"AI Allocation $x_A^*$ (MW)")
ax.set_title("(c) Allocation & Pareto Frontier")
ax.legend(fontsize=8.5, loc="upper right")
ax.grid(True, alpha=0.3)
ax.set_ylim(0, alpha / beta * 1.1)

plt.tight_layout()

# Save
out_dir = os.path.join(project_root, "output", "figures")
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, "fig_ai_resource_pareto.png")
plt.savefig(out_path, dpi=300, bbox_inches="tight")
print(f"Figure saved to: {out_path}")
plt.close()
