"""
Figure: Cooperative AI Equilibrium
===================================

Three-panel figure:
  (a) Payoff matrix heatmap (T, R, P, S across friction regimes)
  (b) Cooperation frequency vs δ for N = 2, 10, 100
  (c) Invasion barrier: defector payoff vs cooperator fraction

Data source: output/data/fig_cooperative_equilibrium.npz
  (generated by scripts/simulations/applications/verify_cooperative_equilibrium.py)

Output: output/figures/fig_cooperative_equilibrium.png

Run:  python scripts/figures/fig_cooperative_equilibrium.py
"""

from __future__ import annotations

import sys
import os

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
from modules.plotting import paper_style
from modules.figure_data import load_figure_data

paper_style()

# ---------------------------------------------------------------------------
# Load verified data
# ---------------------------------------------------------------------------
data = load_figure_data("cooperative_equilibrium")

Phi_vals = data["Phi_vals"]
payoff_matrix = data["payoff_matrix"]
N_range = data["N_range"]
phi_scenarios = data["phi_scenarios"]
delta_N_curves = data["delta_N_curves"]
delta_range_invasion = data["delta_range_invasion"]
payoff_ratio = data["payoff_ratio"]
ds_base = float(data["delta_star_base"])
alpha_coop = float(data["alpha_coop"])
c_contrib = float(data["c_contrib"])
E_bar = float(data["E_bar"])

# ---------------------------------------------------------------------------
# Figure: 3 panels
# ---------------------------------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))

# ===== Panel (a): Payoff matrix heatmap across friction regimes =====
ax = axes[0]

labels_Phi = [f"Φ={p}" for p in Phi_vals]
payoff_names = ['T', 'R', 'P', 'S']

vmin, vmax = payoff_matrix.min(), payoff_matrix.max()
abs_max = max(abs(vmin), abs(vmax))
norm = mcolors.TwoSlopeNorm(vmin=-abs_max, vcenter=0, vmax=abs_max)

im = ax.imshow(payoff_matrix, cmap='RdYlGn', norm=norm, aspect='auto')
ax.set_xticks(range(4))
ax.set_xticklabels(payoff_names, fontsize=11)
ax.set_yticks(range(len(Phi_vals)))
ax.set_yticklabels(labels_Phi, fontsize=10)
ax.set_xlabel('Payoff Type', fontsize=11)
ax.set_ylabel('Friction Regime', fontsize=11)
ax.set_title('(a) Payoff Matrix Across\nFriction Regimes', fontsize=12)

for i in range(len(Phi_vals)):
    for j in range(4):
        color = 'white' if abs(payoff_matrix[i, j]) > 30 else 'black'
        ax.text(j, i, f'{payoff_matrix[i, j]:.0f}', ha='center', va='center',
                fontsize=10, fontweight='bold', color=color)

cbar = plt.colorbar(im, ax=ax, shrink=0.8, pad=0.02)
cbar.set_label('Payoff (energy units)', fontsize=9)

# ===== Panel (b): Cooperation threshold δ* vs N for different φ₀ =====
ax = axes[1]

colors = ['#d62728', '#ff7f0e', '#2ca02c', '#1f77b4']
line_styles = ['--', '-.', '-', ':']

for i, (phi, col, ls) in enumerate(zip(phi_scenarios, colors, line_styles)):
    label = f'$\\varphi_0 = {phi}$'
    ax.plot(N_range, delta_N_curves[i], color=col, ls=ls, linewidth=2, label=label)

    # Plot limit
    ds_inf = c_contrib / (alpha_coop * c_contrib + phi * E_bar) if phi > 0 else 0.5
    ax.axhline(y=ds_inf, color=col, ls=':', alpha=0.3, linewidth=1)

ax.axhline(y=0.5, color='gray', ls=':', alpha=0.5, linewidth=1)
ax.text(180, 0.51, '$\\delta = 0.5$', fontsize=8, color='gray', ha='right')

ax.set_xlabel('Number of Agents $N$', fontsize=11)
ax.set_ylabel('Critical Discount Factor $\\delta_N^*$', fontsize=11)
ax.set_title('(b) N-Player Cooperation\nThreshold vs. Friction', fontsize=12)
ax.set_xlim(3, 200)
ax.set_ylim(0, 0.55)
ax.legend(fontsize=9, loc='lower right')
ax.grid(True, alpha=0.3)

# ===== Panel (c): Invasion barrier — payoff ratio vs δ =====
ax = axes[2]

ax.plot(delta_range_invasion, payoff_ratio, color='#d62728', linewidth=2.5,
        label='$V_{\\mathrm{ALLD}} / V_{\\mathrm{TFT}}$')
ax.axhline(y=1.0, color='gray', ls='--', alpha=0.6, linewidth=1)
ax.axvline(x=ds_base, color='#2ca02c', ls='--', alpha=0.8, linewidth=1.5,
           label=f'$\\delta^* = {ds_base:.3f}$')

ax.fill_between(delta_range_invasion, payoff_ratio, 1.0,
                where=(payoff_ratio > 1.0), alpha=0.15, color='#d62728',
                label='Defection profitable')
ax.fill_between(delta_range_invasion, payoff_ratio, 1.0,
                where=(payoff_ratio <= 1.0), alpha=0.15, color='#2ca02c',
                label='Cooperation stable')

# Mark specific points
T_base = float(data["T_base"])
R_base = float(data["R_base"])
P_base = float(data["P_base"])
for d_point, label_text in [(0.5, '$\\delta=0.5$'), (0.8, '$\\delta=0.8$')]:
    v_c = R_base / (1 - d_point)
    v_d = T_base + d_point * P_base / (1 - d_point)
    r = v_d / v_c
    ax.plot(d_point, r, 'ko', markersize=6, zorder=5)
    ax.annotate(f'{label_text}\nratio={r:.2f}',
                xy=(d_point, r), xytext=(d_point + 0.05, r + 0.15),
                fontsize=8, ha='left',
                arrowprops=dict(arrowstyle='->', color='black', lw=0.8))

ax.set_xlabel('Discount Factor $\\delta$', fontsize=11)
ax.set_ylabel('Payoff Ratio $V_{\\mathrm{ALLD}} / V_{\\mathrm{TFT}}$', fontsize=11)
ax.set_title('(c) Invasion Barrier:\nDefector vs. Cooperator', fontsize=12)
ax.set_xlim(0, 1)
ax.set_ylim(-1, 2.5)
ax.legend(fontsize=8, loc='upper right')
ax.grid(True, alpha=0.3)

# ---------------------------------------------------------------------------
# Save
# ---------------------------------------------------------------------------
plt.tight_layout()
out_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'output', 'figures')
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, 'fig_cooperative_equilibrium.png')
plt.savefig(out_path, dpi=300, bbox_inches='tight')
print(f"Saved: {out_path}")
plt.close()
